version: "3"
networks:
  myevents:

services:

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - 5672:5672
    networks:
      - myevents

  prometheus:
    image: prom/prometheus:v1.6.1
    ports:
      - 9090:9090
    volumes:
      - "./prometheus.yml:/etc/prometheus/prometheus.yml"
      - "prometheus-data:/prometheus"
    networks:
      - myevents
      - monitoring

  grafana:
    image: grafana/grafana:4.2.0
    ports:
      - 3000:3000
    networks:
      - monitoring

  events-db:
    image: mongo
    networks:
      - myevents

  bookings-db:
    image: mongo
    networks:
    - myevents

  events:
    build: ./eventsservice/
    ports:
      - "8181:8181"
      - "9100:9100"
    networks:
      - myevents
    environment:
      - AMQP_BROKER_URL=amqp://guest:guest@rabbitmq:5672/
      - MONGO_URL=mongodb://events-db/events
  
  bookings:
    build: ./bookingservice/
    ports:
      - "8282:8181"
      - "9101:9100"
    networks:
      - myevents
    environment:
      - AMQP_BROKER_URL=amqp://guest:guest@rabbitmq:5672/
      - MONGO_URL=mongodb://bookings-db/bookings

  frontend: 
      build: ./frontend/microservice-example-frontend/
      ports:
        - "80:80"