version: "3"
networks:
  myevents:

services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - 5672:5672
    networks:
      - myevents
    
  events-db:
    image: mongo
    networks:
      - myevents

  bookings-db:
    image: mongo
    networks:
    - myevents

  events:
    build: ./eventsservice/
    ports:
      - "8181:8181"
    networks:
      - myevents
    environment:
      - AMQP_BROKER_URL=amqp://guest:guest@rabbitmq:5672/
      - MONGO_URL=mongodb://events-db/events
  
  bookings:
    build: ./bookingservice/
    ports:
      - "8282:8181"
    networks:
      - myevents
    environment:
      - AMQP_BROKER_URL=amqp://guest:guest@rabbitmq:5672/
      - MONGO_URL=mongodb://bookings-db/bookings

  frontend: 
      build: ./frontend/microservice-example-frontend/
      ports:
        - "80:80"